export const POST_ACTION_TYPE = {
    POST_FETCH_SUCCESS : 'POST_FETCH_SUCCESS',
    POST_FETCH_START : 'POST_FETCH_START',
    POST_FETCH_FAILED : 'POST_FETCH_FAILED',
    ADD_POST_START: 'ADD_POST_START',
    ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
    ADD_POST_FAILED: 'ADD_POST_FAILED',
    DELETE_POST_START: 'DELETE_POST_START',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILED: 'DELETE_POST_FAILED',
    UPDATE_POST_START: 'UPDATE_POST_START',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILED: 'UPDATE_POST_FAILED'
}