export const COMMENT_ACTION_TYPE = {
    ADD_COMMENT_START: 'ADD_COMMENT_START',
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILED: 'ADD_COMMENT_FAILED',
    FETCH_COMMENT_START: 'FETCH_COMMENT_START',
    FETCH_COMMENT_SUCCESS: 'FETCH_COMMENT_SUCCESS',
    FETCH_COMMENT_FAILED: 'FETCH_COMMENT_FAILED',
    UPDATE_COMMENT_LIKE: 'UPDATE_COMMENT_LIKE'
}